"""Stub/Mock test case catalog for no-hardware validation."""

STUBMOCK_CASES = [
    {
        "id": "A1-logic-wheelchair-priority",
        "layer": "A",
        "target": "logic.decide_light",
        "scenario": "Wheelchair present and low car load should trigger PED_GREEN with capped duration.",
        "expected": {"command": "PED_GREEN_60", "light_state": "PED_WHEELCHAIR"},
    },
    {
        "id": "A2-control-emergency-y2r",
        "layer": "A",
        "target": "services.control.tick_emergency_phase",
        "scenario": "Emergency phase should progress YELLOW -> ALL_RED -> EMERGENCY_RED -> KEEP.",
        "expected": {
            "sequence_prefix": ["EMERGENCY_YELLOW", "EMERGENCY_ALL_RED", "EMERGENCY_RED"],
            "final_command": "KEEP",
        },
    },
    {
        "id": "A3-detect-car-lane-counts",
        "layer": "A",
        "target": "services.detect_car.process_car_data",
        "scenario": "Stubbed detections should update cars_total and lane_counts deterministically.",
        "expected": {"cars_total": 2, "lane_counts": [1, 0, 1], "tidal_direction": "BALANCED"},
    },
    {
        "id": "A4-digital-twin-compare",
        "layer": "A",
        "target": "services.digital_twin.run_what_if_compare",
        "scenario": "Recorded frames >=15 should produce successful strategy comparison.",
        "expected": {"success": True, "min_strategies": 2},
    },
    {
        "id": "B1-stats-contract",
        "layer": "B",
        "target": "GET /stats",
        "scenario": "Stats response should include command/count fields and omit plates list payload.",
        "expected": {
            "status_code": 200,
            "required_keys": ["cars", "persons", "wheelchairs", "command", "lane_counts", "tidal_direction"],
            "forbidden_keys": ["plates"],
        },
    },
    {
        "id": "B2-detect-empty-payload",
        "layer": "B",
        "target": "POST /detect_*",
        "scenario": "Empty octet-stream payload should be rejected by detect routes.",
        "expected": {"status_code": 400},
    },
    {
        "id": "B3-emergency-route-clear",
        "layer": "B",
        "target": "POST /trigger_emergency + /clear_emergency",
        "scenario": "Trigger then clear should leave command in KEEP.",
        "expected": {"trigger_status": 200, "clear_status": 200, "final_command": "KEEP"},
    },
    {
        "id": "B4-lane-boundary-validation",
        "layer": "B",
        "target": "POST /lane_boundaries",
        "scenario": "Invalid boundary ordering should return 400 with success=false.",
        "expected": {"status_code": 400, "success": False},
    },
    {
        "id": "C1-stream-replay-mock-http",
        "layer": "C",
        "target": "simulate_car_stream.main",
        "scenario": "Replay script should send frames to mocked /detect_car and /detect_person.",
        "expected": {"exit_code": 0, "detect_car_hits_gt": 0, "detect_person_hits_gt": 0},
    },
    {
        "id": "D1-mega-emergency-clear-translation",
        "layer": "D",
        "target": "Mega WiFi polling contract replay",
        "scenario": "Server sequence ending in KEEP should imply an EMERGENCY_CLEAR dispatch before KEEP.",
        "expected": {"translated_suffix": ["EMERGENCY_CLEAR", "KEEP"]},
    },
    {
        "id": "D2-mega-carcount-fallback-contract",
        "layer": "D",
        "target": "GET /stats field contract",
        "scenario": "Stats must expose cars (fallback when cars_total absent).",
        "expected": {"cars_key_present": True},
    },
    {
        "id": "E1-decode-xor-roundtrip",
        "layer": "E",
        "target": "services.decode.decode_image",
        "scenario": "XOR encode → decode roundtrip should preserve image dimensions.",
        "expected": {"width": 32, "height": 24, "mode": "RGB"},
    },
    {
        "id": "E2-detect-person-classification",
        "layer": "E",
        "target": "services.detect_person.classify_person_label",
        "scenario": "Label classification must correctly categorize person/wheelchair/ignore.",
        "expected": {
            "person": "person",
            "peoplewheelchair": "people_wheelchair",
            "wheelchair": "wheelchair",
            "dog": "ignore",
        },
    },
    {
        "id": "E3-detect-person-counting",
        "layer": "E",
        "target": "services.detect_person.process_person_data",
        "scenario": "Stubbed model with 2 persons + 1 wheelchair user → p=3, w=1.",
        "expected": {"persons": 3, "wheelchairs": 1},
    },
    {
        "id": "E4-detect-plate-stub-ocr",
        "layer": "E",
        "target": "services.detect_plate.process_plate_data",
        "scenario": "Stubbed model + OCR should populate plates_this_frame and history.",
        "expected": {"plates_found": 1, "text": "TEST999"},
    },
    {
        "id": "F1-mega-json-parser",
        "layer": "F",
        "target": "ArduinoMega parseJsonString/parseJsonLong",
        "scenario": "Python stub of JSON parsers should match C++ behaviour for both compact and spaced forms.",
        "expected": {"command_compact": "CAR_GREEN", "command_spaced": "PED_GREEN_10", "cars_total": 5},
    },
    {
        "id": "F2-mega-brightness-control",
        "layer": "F",
        "target": "ArduinoMega BrightnessControl",
        "scenario": "Illuminance→brightness mapping: high=255, low=135, mid=linear.",
        "expected": {"high": 255, "low": 135, "mid_70": 195},
    },
    {
        "id": "F3-mega-fsm-emergency-sequence",
        "layer": "F",
        "target": "ArduinoMega processEsp32Command FSM",
        "scenario": "Emergency sequence YELLOW→ALL_RED→RED_HOLD→CLEAR should transition correctly.",
        "expected": {
            "after_yellow": "EMERGENCY_YELLOW",
            "after_all_red": "EMERGENCY_ALL_RED",
            "after_red": "EMERGENCY_RED_HOLD",
            "after_clear": "PED_RED_WAIT",
        },
    },
    {
        "id": "F4-mega-pressure-jam",
        "layer": "F",
        "target": "ArduinoMega readPressureSensor + detect_jam",
        "scenario": "Sustained pressure with high car count should trigger jam detection.",
        "expected": {"jam": True, "cooling_period": True},
    },
    {
        "id": "F5-mega-rfid-uid-match",
        "layer": "F",
        "target": "ArduinoMega RFID UID matching",
        "scenario": "Known emergency UIDs should match; unknown UIDs should not.",
        "expected": {"known_match": True, "unknown_match": False},
    },
    {
        "id": "G1-logic-idle-keep",
        "layer": "G",
        "target": "logic.decide_light",
        "scenario": "Zero people + zero vehicles + already CAR_GREEN → KEEP.",
        "expected": {"command": "KEEP", "light_state": "CAR_GREEN"},
    },
    {
        "id": "G2-logic-wheelchair-disabled",
        "layer": "G",
        "target": "logic.decide_light",
        "scenario": "wheelchair_priority_active=False should skip wheelchair priority path.",
        "expected": {"not_wheelchair_state": True},
    },
]


